### ISSUE TITLE
Affected Projects listing all modules

### ISSUE THREAD

**Issue by mshearer123** [ismaeldivita/change-tracker-plugin#5] opened 2020-08-17 14:50 UTC
Hi,

Thanks for this project, I think it's going to make a huge difference to our CI environment.

At the minute running `changedModules` lists all the modules in the app as affected.
Is there anyway to debug what is going on?  I can see `logger.isInfoEnabled` but not sure how to toggle that.

**Comment by ismaeldivita** [comment] 2020-08-17 15:25
Hi @mshearer123
If you enable the Info level you gonna be able to see which files changed, their modules and the impact of the changes.
Just add -i when you run your command

```
./gradlew testChangesModules -i
```

Not sure if it's your case, but normally when you're setuping the plugin for the first time, it will trigger the task for all modules since you're modifying the root `build.gradle`. Next PR's should be fine

**Comment by mshearer123** [comment] 2020-08-18 12:29
Thanks @ismaeldivita 

unfortunately we use this sort of code below in settings.gradle to allow modules within folders
```
file("features").safeListFiles { dir ->
  include("features-${dir.name}")
  project(":features-${dir.name}").projectDir = dir
}
```
We'll revisit if we can change that

**Comment by ismaeldivita** [comment] 2020-08-18 12:54
This code seems to just register the modules inside "features" folder automatically. I can't see a problem and this should not impact on the plugin.

The plugin should work fine with nested sub-projects like this.
`:app`
`:foo`
`:foo:bar`
`:foo:bar:z`

If you could share more details or provide a sample repo reproducing the problem I can take a look.

**Comment by mshearer123** [comment] 2020-08-18 13:01
I think it's the filepath throwing it.
for 
`/features/feature1` 

this line in the project locator
`(projectPaths.indices).all { projectPaths[it] == filePaths[it] }`

will compare `features-feature1` with `features`

This is obviously incorrect, but works for our setup
`(projectPaths.indices).all { projectPaths[it] == (filePaths[it] + "-" + filePaths[it + 1]) }`

**Comment by mshearer123** [comment] 2020-08-18 14:00
Sample with the issue - https://github.com/mshearer123/ChangeTrackerExample

in branch `test` with a change in only feature1

output from task
```
Changed Files
- features/feature2/src/main/java/com/mas/feature2/SecondFragment.kt

Changed Projects
- null

Affected Projects
- project ':app'
- project ':features-feature1'
- project ':features-feature2'
```

**Comment by ismaeldivita** [comment] 2020-08-18 14:15
Got it

I shouldn't use the project `path` to search for a module, but the `projectDir` instead.
I'll fix it

**Comment by mshearer123** [comment] 2020-08-18 14:27
@ismaeldivita Brilliant.

One other thing, the `remote` value, does that expect something like `https://github.com/mshearer123/ChangeTrackerExample.git` ?

**Comment by ismaeldivita** [comment] 2020-08-18 14:46
Just the remote name like `upstream` or `origin`.

**Comment by ismaeldivita** [comment] 2020-08-18 18:27
Let me know if [0.7.3](https://github.com/ismaeldivita/change-tracker-plugin/releases/tag/0.7.3) fixes your problem

**Comment by mshearer123** [comment] 2020-08-19 10:19
@ismaeldivita works perfectly, thanks very much

**Comment by ismaeldivita** [comment] 2020-08-19 10:57
Nice, I'll close this one.

**Closed as completed by ismaeldivita** 2020-08-19 10:57 UTC
